### ISSUE TITLE
the problem of Estimated LD50

### ISSUE THREAD

**Issue by uyghbo** [nathanpincus/PA_Virulence_Prediction#1]
Dear author:
    Recently, I'm reading your excellent work "A Genome-Based Model to Predict the Virulence of Pseudomonas aeruginosa Isolates". And I'm trying to determine the Estimated LD50 using your data ("TABLE S2"). I used drc package in R, but encountered several errors which confused me a lot.

    My code are look like this:
library(openxlsx)
KP <- read.xlsx('inline-supplementary-material-2.xlsx',
                startRow=2)
KP <- KP[,-2]
colnames(KP) <- c("type", "conc", "total", "dead")
KP.LL.2 <- drm(dead/total ~ conc, type, weights = total,data = KP,
                       fct = LL.2(), type = "binomial")
ED(KP.LL.2, 50, interval = "delta")

and it returns "Error in solve.default(object$fit$hessian) :
apack routine dgesv: system is exactly singular: U[25,25] = 0"

It seems that the problem is caused by the original data in 'Table S2' ?

would you please provide me your code for reference, it will help me a lot!

Best regards,
Sunny

**Comment by nathanpincus** [comment]
I have added the LD50 estimation scripts to the data folder of this repository, along with the corresponding input data.  See LD50_estimates_training.R for an example.

Best,
Nathan
